Repository Arsenic-ATG/Emacs-config, pull requests merged in 2022-11, with the labels that each got.

#28 New-package: expand region
  elisp/init-expand-region.el
  init.el
Labels: new package

#30 Org: defer org tempo after org mode
  elisp/init-org.el
Labels: optimisation

#31 New-package: Org noter
  elisp/init-org.el
Labels: new package

#35 Update init-theme.el
  elisp/init-theme.el
Labels: enhancement

#38 dired: defer dired-single after dired
  elisp/init-dired.el
Labels: optimisation

#41 dired-hacks: add dired-rainbow
  elisp/init-dired.el
Labels: new package

#43 fix: No such file or directory, init-format
  elisp/init-format.el
Labels: bug

#45 org-noter: defer on "org-noter" command
  elisp/init-org.el
Labels: optimisation

#49 Theme: add arsenic-flate and doom-flate
  themes/Arsenic-flate-theme.el
  themes/doom-flate-theme.el
Labels: Theme

#56 Theme: change magit and dashboard colors
  themes/Arsenic-flate-theme.el
Labels: Theme

#58 images: renamee screen shots
  images/ss1.png
  images/ss2.png
Labels: bug
